# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyLittleTranslator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyLittleTranslator
  pod 'Google-Mobile-Ads-SDK'

  target 'MyLittleTranslatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyLittleTranslator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyLittleTranslator-tvOS

  target 'MyLittleTranslator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
